# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
