# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20171001_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_zip_code',
            field=models.CharField(default='Nairobi', max_length=100),
            preserve_default=False,
        ),
    ]
